<?
/**
 * @var array  $menuItems
 * @var string $active
 */
?>
<? foreach ($menuItems as $item) { ?>
    <div class="contentPageMenu mb">
        <h2><?= $item['name'] ?></h2>
        <ul class="mt mtO">
            <? foreach ($item['sub'] as $url => $title) { ?>
                <? if ($title == 'divider') { ?>
                    <li class="divider"></li>
                <? } else { ?>
                    <li><a href="<?= $url ?>" <?= ($url == $active) ? 'class="active"' : '' ?>><?= $title ?></a></li>
                <? } ?>
            <? } ?>
        </ul>
    </div>
<? } ?>
