<?
/**
 * @var ob_order               $order
 * @var int                    $orderId
 * @var array                  $productIds
 * @var order_products_model[] $orderProducts
 * @var bool                   $firstOrder
 * @var string                 $orderCode
 * @var float                  $orderTotalAmount
 * @var float                  $orderTotalTax
 * @var array                  $channelData
 */
?>
<?
$productTotalWithoutTax = 0;
foreach ($orderProducts as $orderProduct) {
    $productTotalWithoutTax += $orderProduct->quantity * ($orderProduct->order_sale / (100 + $orderProduct->tax_rate) * 100);
}
?>
<? /* START Google Adwords */ ?>
<? if (\TeknoETicaret\Config\Settings::get('adwords.remarketing.enabled')) { ?>
    <!-- Google Code for Dönüşümler Conversion Page -->
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = <?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>;
        var google_conversion_language = "en";
        var google_conversion_format = 3;
        var google_conversion_color = "ffffff";
        var google_conversion_label = "BMP4CNK31VwQjoag-AM";
        var google_conversion_value = <?=$orderTotalAmount?>;
        var google_conversion_currency = "TRY";
        var google_remarketing_only = false;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt=""
                    src="//www.googleadservices.com/pagead/conversion/<?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>/?label=BMP4CNK31VwQjoag-AM&amp;guid=ON&amp;script=0&amp;value=<? echo $orderTotalAmount ?>&amp;conversion_currency=TRY"/>
        </div>
    </noscript>
    <? /* END Google Adwords */ ?>
    <? /* BEGIN - Adwords Remarketing */ ?>
    <script type="text/javascript">
        var google_tag_params = {
            ecomm_prodid: ["<?=implode('","', $productIds)?>"],
            ecomm_pagetype: "purchase",
            ecomm_totalvalue: <?=$orderTotalAmount?>
        };
    </script>
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = <?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        var google_conversion_format = 3;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt=""
                    src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
    <? /* END - Adwords Remarketing */ ?>
<? } ?>
<? /* CRITEO Begin */ ?>
<? if (\TeknoETicaret\Config\Settings::get('tracking.criteo.enabled') && \TeknoETicaret\Config\Settings::get('tracking.criteo.accountid') > 0) { ?>
    <script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="async"></script>
    <script type="text/javascript">
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
            {event: "setAccount", account: <?=\TeknoETicaret\Config\Settings::get('tracking.criteo.accountid')?>},
            <? if (session::isMember()) { ?>
            {event: "setHashedEmail", email: "<?= md5(strtolower(singleton::member(session::memberId())->email)) ?>"},
            <? } ?>
            {event: "setSiteType", type: "<?=(request::getDeviceType() == request::DEVICE_PHONE ? "m" : (request::getDeviceType() == request::DEVICE_TABLET ? "t" : "d"))?>"},
            {
                event: "trackTransaction",
                id: "<?= $orderCode ?>",
                item: <?
                $items = [];
                foreach ($orderProducts as $orderProduct) {
                    $items[] = ['id' => $orderProduct->product_id, 'price' => $orderProduct->order_sale, 'quantity' => $orderProduct->quantity];
                }
                echo json_encode($items);
                ?>
            }
        );
    </script>
<? } ?>
<? /* CRITEO END */ ?>
<!-- Offer Conversion: Pink&More [Satış/CPS] -->
<iframe src="https://ad.adrttt.com/SL7SX?adv_sub=<?= $orderCode ?>&amount=<?= $productTotalWithoutTax ?>" scrolling="no" frameborder="0" width="1" height="1"></iframe>
<!-- // End Offer Conversion -->
<!-- Adform Tracking Code BEGIN -->
<?
$adformProducts = [];
foreach ($orderProducts as $orderProduct) {
    $adformProducts[] = [
        'productid' => $orderProduct->product_id,
        'step' => 4,
    ];
}
?>
<script type="text/javascript">
    window._adftrack = {
        pm: 711599,
        pagename: encodeURIComponent(''),
        divider: encodeURIComponent('|'),
        order: {
            sales: '<?= $productTotalWithoutTax ?>',
            orderid: '<?= $orderCode ?>',
            itms: <?=json_encode($adformProducts, JSON_UNESCAPED_UNICODE)?>
        }
    };
    (function () {
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = 'https://track.adform.net/serving/scripts/trackpoint/async/';
        var x = document.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
    })();
</script>
<noscript>
    <p style="margin:0;padding:0;border:0;">
        <img src="https://track.adform.net/Serving/TrackPoint/?pm=711599&ADFPageName=&ADFdivider=|" width="1" height="1" alt=""/>
    </p>
</noscript>
<!-- Adform Tracking Code END -->
<!---------------------------checkout Pixel Start---------------------------------- -->
<script type='text/javascript'>
    rtgsettings = {
        'pdt_id': '<?=$productIds?>',
        'pdt_sku': '',
        'pdt_category_list': '',
        'ty_orderid': '<?= $orderCode ?>',
        'ty_orderamt': '<?=$orderTotalAmount?>',
        'ty_orderdate': '<?=date('Y.m.d')?>',
        'ty_orderstatus': '',
        'ty_currency': 'TRY',
        'ty_cusname': '',
        'ty_cusid': '<?=$order->member_id?>',
        'ty_custype': '',
        'ty_cuscoupon': '',
        'pagetype': 'checkout',
        'key': 'RA',
        'token': 'PinkMore_TR',
        'layer': 'iframe'
    };
    (function (d) {
        var s = d.createElement('script');
        s.async = true;
        s.id = 'madv2014rtg';
        s.type = 'text/javascript';
        s.src = (d.location.protocol == 'https:' ? 'https:' : 'http:') + '//www.mainadv.com/Visibility/Rtgra2-min.js';
        var a = d.getElementsByTagName('script')[0];
        a.parentNode.insertBefore(s, a);
    }(document));
</script>
<!---------------------------Checkout Pixel END---------------------------------- -->
