<? if (\TeknoETicaret\Config\Settings::get('adwords.remarketing.enabled')) { ?>
    <? /* BEGIN - Adwords Remarketing */ ?>
    <script type="text/javascript">
        var google_tag_params = {
            ecomm_prodid: "",
            ecomm_pagetype: "home"
        };
    </script>
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = <?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        var google_conversion_format = 3;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt=""
                    src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
    <? /* END - Adwords Remarketing */ ?>
<? } ?>
<? /* CRITEO Begin */ ?>
<? if (\TeknoETicaret\Config\Settings::get('tracking.criteo.enabled') && \TeknoETicaret\Config\Settings::get('tracking.criteo.accountid') > 0) { ?>
    <script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="async"></script>
    <script type="text/javascript">
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
            {event: "setAccount", account: <?=\TeknoETicaret\Config\Settings::get('tracking.criteo.accountid')?>},
            <? if (session::isMember()) { ?>
            {event: "setHashedEmail", email: "<?= md5(strtolower(singleton::member(session::memberId())->email)) ?>"},
            <? } ?>
            {event: "setSiteType", type: "<?=(request::getDeviceType() == request::DEVICE_PHONE ? "m" : (request::getDeviceType() == request::DEVICE_TABLET ? "t" : "d"))?>"},
            {event: "viewHome"}
        );
    </script>
<? } ?>
<? /* CRITEO END */ ?>
<script type='text/javascript'>
    rtgsettings = {
        'pdt_url': '<?=json_encode('http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'])?>',
        'pagetype': 'home',
        'key': 'RA',
        'token': 'PinkMore_TR',
        'layer': 'iframe'
    };
    (function (d) {
        var s = d.createElement('script');
        s.async = true;
        s.id = 'madv2014rtg';
        s.type = 'text/javascript';
        s.src = (d.location.protocol == 'https:' ? 'https:' : 'http:') + '//www.mainadv.com/Visibility/Rtgra2-min.js';
        var a = d.getElementsByTagName('script')[0];
        a.parentNode.insertBefore(s, a);
    }(document));
</script>
