<?
/**
 * @var ob_product[] $products
 */
?>
<!-- Adform Tracking Code BEGIN -->
<?
$adformProducts = [];
foreach ($products as $obProduct) {
    $adformProducts[] = [
        'productid' => $obProduct->product_id,
        'categoryname' => $obProduct->category_name,
        'step' => 3,
    ];
}
?>
<script type="text/javascript">
    window._adftrack = {
        pm: 711599,
        pagename: encodeURIComponent(''),
        divider: encodeURIComponent('|'),
        order: {
            itms: <?=json_encode($adformProducts, JSON_UNESCAPED_UNICODE)?>
        }
    };
    (function () {
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = 'https://track.adform.net/serving/scripts/trackpoint/async/';
        var x = document.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
    })();
</script>
<noscript>
    <p style="margin:0;padding:0;border:0;">
        <img src="https://track.adform.net/Serving/TrackPoint/?pm=711599&ADFPageName=&ADFdivider=|" width="1" height="1" alt=""/>
    </p>
</noscript>
<!-- Adform Tracking Code END -->
