<?
/**
 * @var ob_product                           $obProduct
 * @var array                                $productGroupLinks
 * @var bool                                 $hasVariants
 * @var array                                $variantProperties
 * @var array                                $productPhotos
 * @var string                               $mainProductUrl
 * @var string                               $FacebookAppID
 * @var string                               $TwitterAccount
 * @var \TeknoETicaret\Object\Product\Rating $rating
 * @var int                                  $reviewCount
 * @var bool                                 $hasVisiblePriceCampaign
 * @var bool                                 $hasAvailableShoppingCheck
 * @var bool                                 $inStock
 * @var array                                $productHasProperty
 * @var stdClass                             $reviewData
 * @var string                               $semanticData
 * @var array                                $widgets
 * @var int                                  $maxInstallmentCount
 * @var float                                $minInstallmentAmount
 * @var int                                  $bestInstallmentCount
 * @var float                                $bestInstallmentAmount
 * @var string                               $tabs
 */
?>
<? view::show_breadcrumbs() ?>
<div class="clear"></div>
<? if (session::isStaff()) { ?>
    <div class="pull-right">
        <a title="Ürünü Düzenle" data-toggle="tooltip" data-placement="left" target="_blank" style="font-size:18px"
                href="<?= app::getUrl(app::APP_TAG_OASIS, 'http') . "/product/summary/" . $obProduct->product_id ?>"> <i class="glyphicon glyphicon-edit"></i> </a>
    </div>
<? } ?>
<h1 class="productName"><?= $obProduct->full_name ?></h1>
<div class="clear"></div>
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12 imgArea">
        <div class="owl-carousel owl-product">
            <? foreach ($productPhotos as $key => $photo) { ?>
                <img src="<?= $photo['normal'] ?>" alt="">
            <? } ?>
        </div>
        <?= \TeknoETicaret\Widget\Block::addBlock('productPhotoUnder',
            ['productId' => $obProduct->product_id, 'categoryId' => $obProduct->category_id, 'brandId' => $obProduct->brand_id,]
        ); ?>
    </div>
    <!-- imgArea -->
    <div class="col-md-6 col-sm-6 col-xs-12 productFeature">
        <div class="star">
            <div class="productRating pull-left"></div>
            &nbsp; <span><?= number_format($rating->getScore(), 1) ?></span>
            <script type="text/javascript">
                $(function () {
                    $('.productRating').raty({
                        score: <?= $rating->getScore() ?>,
                        click: function (score) {
                            $.post('/product/saveRating', {product_id: '<?=$obProduct->product_id?>', rating_score: score}, function (data) {
                                if (data.readonly) {
                                    $('.productRating').raty({readOnly: true, score: <?= $rating->getScore() ?>});
                                }
                                if (typeof data.message !== "undefined") {
                                    alert(data.message);
                                }
                            });
                        }
                    });
                });
            </script>
        </div>
        <div class="yOku"><a href="javascript:" onclick="$('a[href=#tabComments]').trigger('click')">YORUM OKU<?= ($reviewCount > 0 ? " (" . $reviewCount . ")" : "") ?></a></div>
        <!-- stars -->
        <div class="clear"></div>
        <div id="productData">
            <? if (count($productGroupLinks)) { ?>
                <? foreach ($productGroupLinks as $propertyId => $propertyData) { ?>
                    <div class="productOptionSelector">
                        <label><?= $propertyData['name'] ?></label>
                        <div class="clear"></div>
                        <div class="bpG">
                            <? foreach ($propertyData['options'] AS $optionId => $optionData) { ?>
                                <a href="<?= $optionData['url'] ?>"
                                        class="bgGroup <?= ((isset($propertyData['selectedOption']) && $propertyData['selectedOption'] == $optionData['option_id']) ? 'active' : '') ?>">
                                    <span class="boyut"><?= $optionData['name'] ?></span>
                                </a>
                            <? } ?>
                        </div>
                    </div>
                <? } ?>
            <? } ?>
            <? if ($hasVariants) { ?>
                <form role="form" action="<?= $mainProductUrl ?>" method="POST" id="formVariant" data-rel="ajax" data-callback="propertyFormCallback">
                    <? foreach ($variantProperties as $propertyId => $propertyData) { ?>
                        <div class="productOptionSelector">
                            <input type="hidden" name="property[<?= $propertyId ?>]" value="<?= $propertyData['selected'] ?>">
                            <label><?= $propertyData['name'] ?></label>
                            <div class="clear"></div>
                            <div class="bpG">
                                <? foreach ($propertyData['options'] AS $optionId => $optionData) { ?>
                                    <a href="javascript:" onclick="chooseProperty('<?= $propertyId ?>', '<?= $optionId ?>')" id="property-<?= $propertyId ?>-<?= $optionId ?>"
                                            class="bgGroup <?= ((isset($propertyData['selected']) && $propertyData['selected'] == $optionId) ? 'active' : '') ?>">
                                        <span class="boyut"><?= $optionData['name'] ?></span>
                                    </a>
                                <? } ?>
                            </div>
                        </div>
                    <? } ?>
                </form>
            <? } ?>
            <? if ($obProduct->is_saleable) { ?>
                <div class="productDetailPrice">
                    <? if ($obProduct->hasBadge(ob_product::BADGE_DISCOUNT)) { ?>
                        <div class="indirim">
                            <span class="iSpan1">%<?= $obProduct->getDiscountPercent() ?></span>
                            <span class="iSpan2">İNDİRİM</span>
                        </div>
                        <!-- indirim -->
                    <? } ?>
                    <div class="rightPrice">
                        <? if ($obProduct->hasBadge(ob_product::BADGE_DISCOUNT)) { ?>
                            <div class="rightPriceOld"><?= icms::format_money($obProduct->getBasePrice()) ?></div>
                        <? } ?>
                        <div class="rightPriceNew"><?= icms::format_money($obProduct->getSalePrice(), null) ?> <span>TL</span></div>
                        <? if ($bestInstallmentCount > 1) { ?>
                            <div class="installment">Peşin Fiyatına <span><?= $bestInstallmentCount ?> x <?= icms::format_money($bestInstallmentAmount) ?></span></div>
                        <? } ?>
                    </div>
                    <!-- rightPrice -->
                </div>
                <!-- productDetailPrice -->
                <div class="piece">
                    <a href="javascript:" onclick="changeQuantity('#productQuantity','down')">-</a>
                    <div>
                        <input name="quantity" id="productQuantity" class="text-center" value="1" type="text" min="1" max="<?= $obProduct->saleableProductCount() ?>"
                                onblur="changeQuantity($(this))">
                        <label for="productQuantity">ADET</label>
                    </div>
                    <a href="javascript:" onclick="changeQuantity('#productQuantity','up')">+</a>
                </div>
                <!-- piece -->
                <div class="clear"></div>
                <input type="hidden" id="productId" value="<?= $obProduct->product_id ?>"/>
                <input type="hidden" id="fromSource" value="<?= (isset($_GET['from']) ? $_GET['from'] : '') ?>"/>
                <input type="hidden" id="productPrice" value="<?= round($obProduct->getSalePrice(), 2) ?>"/>
                <a href="javascript:" class="gotoBasket" onclick="addToCart($('#productId').val(), $('#productQuantity').val(), $('#fromSource').val());">
                    <span class="gotoBasketImg"></span>
                    <span class="gotoBasketText">SEPETE EKLE</span>
                </a>
                <p class="warning">
                    <? if ($inStock) { ?>
                        Ürün Stoklarımızda! <?= product::findFirstDeliveryDayString() ?> kargoya teslim edilir.
                    <? } else {
                        if ($obProduct->leadTime() == 1) { ?>
                            Hızlı Kargo! 24 saatte kargoya teslim edilir.
                        <? } else { ?>
                            Bu ürün tahmini <?= $obProduct->leadTime() ?> iş gününde kargoya teslim edilir.
                        <? }
                    } ?>
                </p>
            <? } else { ?>
                <? if (\TeknoETicaret\Config\Settings::get('product.notsaleable.showprice') == 1) { ?>
                    <div class="productDetailPrice">
                        <div class="rightPrice">
                            <div class="rightPriceNew"><?= icms::format_money($obProduct->getSalePrice(), null) ?> <span>TL</span></div>
                        </div>
                        <!-- rightPrice -->
                    </div>
                <? } ?>
                <input type="hidden" id="productId" value="<?= $obProduct->product_id ?>"/>
                <input type="hidden" id="fromSource" value="<?= (isset($_GET['from']) ? $_GET['from'] : '') ?>"/>
                <div class="warning">
                    <div class="stockAlertBox">Bu ürün geçici olarak temin edilemiyor.</div>
                    <a class="stockReminder btn btn-info" href="javascript:" onclick="addStockAlert($('#productId').val())" role="button">
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Gelince Haber Ver
                    </a>
                </div>
            <? } ?>
        </div>
        <div class="clear"></div>
        <?= $tabs ?>
    </div>
</div>
<script>
    $(document).on('mouseenter', ".productOptionSelector .boyut", function () {
        var $this = $(this);
        if (this.offsetWidth < this.scrollWidth && !$this.attr('title')) {
            $this.tooltip({
                title: $this.text(),
                placement: "top"
            });
            $this.tooltip('show');
        }
    });
</script>
<!-- procductFeature -->
<div class="clear"></div>
<?= \TeknoETicaret\Widget\Block::addBlock('productUnder',
    [
        'productId' => $obProduct->product_id,
        'categoryId' => $obProduct->category_id,
        'brandId' => $obProduct->brand_id,
    ]
)
?>
