<?
/**
 * @var ob_product                           $obProduct
 * @var array                                $productGroupLinks
 * @var bool                                 $hasVariants
 * @var array                                $variantProperties
 * @var array                                $productPhotos
 * @var string                               $mainProductUrl
 * @var string                               $FacebookAppID
 * @var string                               $TwitterAccount
 * @var \TeknoETicaret\Object\Product\Rating $rating
 * @var int                                  $reviewCount
 * @var bool                                 $hasVisiblePriceCampaign
 * @var bool                                 $hasAvailableShoppingCheck
 * @var bool                                 $inStock
 * @var string                               $productDetails
 * @var array                                $productHasProperty
 * @var stdClass                             $reviewData
 * @var string                               $semanticData
 * @var array                                $widgets
 * @var int                                  $maxInstallmentCount
 * @var float                                $minInstallmentAmount
 * @var int                                  $bestInstallmentCount
 * @var float                                $bestInstallmentAmount
 */
?>
<? view::show_breadcrumbs() ?>
<div class="clear"></div>
<? if (session::isStaff()) { ?>
    <div class="pull-right">
        <a title="Ürünü Düzenle" data-toggle="tooltip" data-placement="left" target="_blank" style="font-size:18px"
                href="<?= app::getUrl(app::APP_TAG_OASIS) . "/product/summary/" . $obProduct->product_id ?>"> <i class="glyphicon glyphicon-edit"></i> </a>
    </div>
<? } ?>
<h1 class="productName"><?= $obProduct->full_name ?></h1>
<div class="clear"></div>
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12 imgArea">
        <div class="owl-product">
            <? foreach ($productPhotos as $key => $photo) { ?>
                <div class="owl-lazy lazySay">
                    <img src="<?= $photo['normal'] ?>" alt="">
                </div>
            <? } ?>
        </div>
        <?= \TeknoETicaret\Widget\Block::addBlock('productPhotoUnder',
            ['productId' => $obProduct->product_id, 'categoryId' => $obProduct->category_id, 'brandId' => $obProduct->brand_id,]
        ); ?>
    </div>
    <!-- imgArea -->
    <div class="col-md-6 col-sm-6 col-xs-12 productFeature">
        <div class="star">
            <div class="productRating pull-left"></div>
            &nbsp; <span><?= number_format($rating->getScore(), 1) ?></span>
            <script type="text/javascript">
                $(function () {
                    $('.productRating').raty({
                        score: <?= $rating->getScore() ?>,
                        click: function (score) {
                            $.post('/product/saveRating', {product_id: '<?=$obProduct->product_id?>', rating_score: score}, function (data) {
                                if (data.readonly) {
                                    $('.productRating').raty({readOnly: true, score: <?= $rating->getScore() ?>});
                                }
                                if (typeof data.message != "undefined") {
                                    alert(data.message);
                                }
                            });
                        }
                    });
                });
            </script>
        </div>
        <div class="yOku"><a href="javascript:" onclick="$('a[href=#tabComments]').trigger('click')">YORUM OKU<?= ($reviewCount > 0 ? " (" . $reviewCount . ")" : "") ?></a></div>
        <!-- stars -->
        <div class="clear"></div>
        <div id="productData">
            <? if (count($productGroupLinks)) { ?>
                <? foreach ($productGroupLinks as $propertyId => $propertyData) { ?>
                    <div class="productOptionSelector">
                        <label><?= $propertyData['name'] ?></label>
                        <div class="clear"></div>
                        <div class="bpG">
                            <? foreach ($propertyData['options'] AS $optionId => $optionData) { ?>
                                <a href="<?= $optionData['url'] ?>"
                                        class="bgGroup <?= ((isset($propertyData['selectedOption']) && $propertyData['selectedOption'] == $optionData['option_id']) ? 'active' : '') ?>">
                                    <span class="boyut"><?= $optionData['name'] ?></span>
                                </a>
                            <? } ?>
                        </div>
                    </div>
                <? } ?>
            <? } ?>
            <? if ($hasVariants) { ?>
                <form role="form" action="<?= $mainProductUrl ?>" method="POST" id="formVariant" data-rel="ajax" data-callback="propertyFormCallback">
                    <? foreach ($variantProperties as $propertyId => $propertyData) { ?>
                        <div class="productOptionSelector">
                            <input type="hidden" name="property[<?= $propertyId ?>]" value="<?= $propertyData['selected'] ?>">
                            <label><?= $propertyData['name'] ?></label>
                            <div class="clear"></div>
                            <div class="bpG">
                                <? foreach ($propertyData['options'] AS $optionId => $optionData) { ?>
                                    <a href="javascript:" onclick="chooseProperty('<?= $propertyId ?>', '<?= $optionId ?>')" id="property-<?= $propertyId ?>-<?= $optionId ?>"
                                            class="bgGroup <?= ((isset($propertyData['selected']) && $propertyData['selected'] == $optionId) ? 'active' : '') ?>">
                                        <span class="boyut"><?= $optionData['name'] ?></span>
                                    </a>
                                <? } ?>
                            </div>
                        </div>
                    <? } ?>
                </form>
            <? } ?>
            <? if ($obProduct->is_saleable) { ?>
                <div class="productDetailPrice">
                    <? if ($obProduct->hasBadge(ob_product::BADGE_DISCOUNT)) { ?>
                        <div class="indirim">
                            <span class="iSpan1">%<?= $obProduct->getDiscountPercent() ?></span>
                            <span class="iSpan2">İNDİRİM</span>
                        </div>
                        <!-- indirim -->
                    <? } ?>
                    <div class="rightPrice">
                        <? if ($obProduct->hasBadge(ob_product::BADGE_DISCOUNT)) { ?>
                            <div class="rightPriceOld"><?= icms::format_money($obProduct->getBasePrice()) ?></div>
                        <? } ?>
                        <div class="rightPriceNew"><?= icms::format_money($obProduct->getSalePrice(), null) ?> <span>TL</span></div>
                        <? if ($bestInstallmentCount > 1) { ?>
                            <div class="installment">Peşin Fiyatına <span><?= $bestInstallmentCount ?> x <?= icms::format_money($bestInstallmentAmount) ?></span></div>
                        <? } ?>
                    </div>
                    <!-- rightPrice -->
                </div>
                <!-- productDetailPrice -->
                <div class="piece">
                    <a href="javascript:;" onclick="quantity('#productQuantity','down')">-</a>
                    <div>
                        <input name="quantity" id="productQuantity" class="text-center" value="1" type="text" min="1" max="<?= $obProduct->saleableProductCount() ?>"
                                onblur="quantity($(this))">
                        <label for="productQuantity">ADET</label>
                    </div>
                    <a href="javascript:;" onclick="quantity('#productQuantity','up')">+</a>
                </div>
                <!-- piece -->
                <div class="clear"></div>
                <input type="hidden" id="productId" value="<?= $obProduct->product_id ?>"/>
                <input type="hidden" id="fromSource" value="<?= (isset($_GET['from']) ? $_GET['from'] : '') ?>"/>
                <input type="hidden" id="productPrice" value="<?= round($obProduct->getSalePrice(), 2) ?>"/>
                <a href="javascript:;" class="gotoBasket" onclick="addToCart($('#productId').val(), $('#productQuantity').val(), $('#fromSource').val());">
                    <span class="gotoBasketImg"></span>
                    <span class="gotoBasketText">SEPETE EKLE</span>
                </a>
                <p class="warning">
                    <? if ($inStock) { ?>
                        Ürün Stoklarımızda! <?= product::findFirstDeliveryDayString() ?> kargoya teslim edilir.
                    <? } else {
                        if ($obProduct->leadTime() == 1) { ?>
                            Hızlı Kargo! 24 saatte kargoya teslim edilir.
                        <? } else { ?>
                            Bu ürün tahmini <?= $obProduct->leadTime() ?> iş gününde kargoya teslim edilir.
                        <? }
                    } ?>
                </p>
            <? } else { ?>
                <? if (\TeknoETicaret\Config\Settings::get('product.notsaleable.showprice') == 1) { ?>
                    <div class="productDetailPrice">
                        <div class="rightPrice">
                            <div class="rightPriceNew"><?= icms::format_money($obProduct->getSalePrice(), null) ?> <span>TL</span></div>
                        </div>
                        <!-- rightPrice -->
                    </div>
                <? } ?>
                <input type="hidden" id="productId" value="<?= $obProduct->product_id ?>"/>
                <input type="hidden" id="fromSource" value="<?= (isset($_GET['from']) ? $_GET['from'] : '') ?>"/>
                <div class="warning">
                    <div class="stockAlertBox">Bu ürün geçici olarak temin edilemiyor.</div>
                    <a class="stockReminder btn btn-info" href="javascript:" onclick="addStockAlert($('#productId').val())" role="button">
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Gelince Haber Ver
                    </a>
                </div>
            <? } ?>
        </div>
        <div class="clear"></div>
        <ul class="nav nav-tabs" role="tablist">
            <li><a href="#tabDetails" role="tab" data-toggle="tab">ÜRÜN AÇIKLAMASI</a></li>
            <li><a href="#tabComments" role="tab" data-toggle="tab">ÜRÜN YORUMLARI</a></li>
            <li><a href="#tabInstallments" role="tab" data-toggle="tab" data-target="#tabInstallments" data-url="/product/get_installment_options/<?= $obProduct->product_id ?>">TAKSİT
                    SEÇENEKLERİ</a></li>
        </ul>
        <!-- tabMenu -->
        <div class="clear"></div>
        <div class="tab-content">
            <div id="tabDetails" class="tab-pane fade in active">
                <div class="mt"><?= $productDetails ?></div>
                <table class="table table-bordered table-striped mt">
                    <colgroup>
                        <col class="col-xs-2">
                        <col class="col-xs-7">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>Özellik</th>
                        <th>Detayları</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if ($productHasProperty) {
                        foreach ($productHasProperty as $row) {
                            ?>
                            <tr>
                                <th><?= $row['key'] ?></th>
                                <td><?= $row['val'] ?></td>
                            </tr>
                            <?
                        }
                    }
                    if ($obProduct->dimension_width > 0 || $obProduct->dimension_height > 0 || $obProduct->dimension_depth > 0) {
                        $dimensionArr = [];
                        if ($obProduct->dimension_width > 0) {
                            $dimensionArr[] = ' Genişlik: ' . $obProduct->dimension_width . 'cm';
                        }
                        if ($obProduct->dimension_height > 0) {
                            $dimensionArr[] = ' Uzunluk: ' . $obProduct->dimension_height . 'cm';
                        }
                        if ($obProduct->dimension_depth > 0) {
                            $dimensionArr[] = ' Derinlik: ' . $obProduct->dimension_depth . 'cm';
                        }
                        ?>
                        <tr>
                            <th>Boyutlar</th>
                            <td><?= (empty($dimensionArr)) ? '' : implode(',', $dimensionArr) ?></td>
                        </tr>
                    <? } ?>
                    <tr>
                        <th>Üretici Kodu</th>
                        <td><?= $obProduct->mpn_code ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div id="tabComments" class="tab-pane fade">
                <?= view::load("product/reviews", ['reviewData' => $reviewData]); ?>
                <div class="row productAddReview">
                    <? if ($reviewData->myCommentWaiting) { ?>
                        <div class="col-xs-12">
                            <h4>YORUMUNUZ ONAY BEKLİYOR</h4>
                            <span class="commentWaiting">Bu ürüne yazdığınız yorum onay bekliyor. Anlayışınız için teşekkür ederiz.</span>
                        </div>
                    <? } elseif (session::memberId()) { ?>
                        <div class="col-xs-12">
                            <h4>YORUMUNUZU YAZIN</h4>
                            <form role="form" action="/product/add_comment" method="POST" onsubmit="return checkCommentForm(this)" id="frmComment">
                                <div class="form-group">
                                    <label for="comments">Ürün Değerlendirmeniz</label>
                                    <div class="personelScore clearfix">
                                        <div class="rating">
                                            <div id="commentStar" class="pull-left"></div>
                                            <span id="ratingHint"></span>
                                        </div>
                                        <script>
                                            $(function () {
                                                $('#commentStar').raty({
                                                    click: function (score) {
                                                        $('input[name=comment_rating]').val(score);
                                                    },
                                                    target: '#ratingHint',
                                                    targetKeep: true
                                                });
                                            });
                                        </script>
                                        <input type="hidden" name="comment_rating" value="0">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="comment_title">Yorum Başlığı</label> <input type="text" id="comment_title" name="comment_title" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="comment_text">Yorumunuz</label> <textarea id="comment_text" name="comment_text" class="form-control" rows="10"></textarea>
                                </div>
                                <input type="hidden" name="product" value="<?= $obProduct->product_id ?>"/> <input type="hidden" name="redirect"
                                        value="<?= $_SERVER['REQUEST_URI'] ?>"/>
                                <button type="submit" class="btn btn-primary mb">Yorumu Gönder</button>
                            </form>
                        </div>
                    <? } else { ?>
                        <div class="col-xs-12 text-center">
                            <a href="<?= $obProduct->getUrl() . "#tabComments" ?>" class="btn btn-primary mt mb login-required">Yorum yapabilmek için oturum açın</a>
                        </div>
                    <? } ?>
                </div>
            </div>
            <div id="tabInstallments" class="tab-pane fade">Yükleniyor...</div>
        </div>
    </div>
</div>
<script>
    $(document).on('mouseenter', ".productOptionSelector .boyut", function () {
        var $this = $(this);
        if (this.offsetWidth < this.scrollWidth && !$this.attr('title')) {
            $this.tooltip({
                title: $this.text(),
                placement: "top"
            });
            $this.tooltip('show');
        }
    });
</script>
<!-- procductFeature -->
<div class="clear"></div>
<?= \TeknoETicaret\Widget\Block::addBlock('productUnder',
    [
        'productId' => $obProduct->product_id,
        'categoryId' => $obProduct->category_id,
        'brandId' => $obProduct->brand_id,
    ]
)
?>
