<div class="header">
    <div class="headerTop container">
        <div class="row">
            <div class="col-xs-3"><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>" title="Pink & More Anasayfa"><img src="<?= $themeDir ?>/img/logo.png" alt="<?= app::getName() ?>"
                        style="width: 150px"></a></div>
            <div class="col-xs-9">
                <div class="row headerSearchCart">
                    <div class="col-xs-3 col-xs-offset-9" style="margin-top: 12px;">
                        <a title="Alışveriş Sepetim" class="btn btn-primary btn-md pull-right" id="cartButton" href="<?= app::getUrl(ACTIVE_APP, "http") ?>/cart">
                            <span class="badge cartItems pull-right"><?= session::getCartProductCount() ?></span> SEPETİM </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
