<div id="footer">
    <div class="footerbottom">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12"><span class="footervalign"><?= \TeknoETicaret\Config\Settings::get('site.name') ?> &copy; <?= date('Y') ?> Her hakkı saklıdır.</span>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12 text-right">
                    <div class="paymentOptions"></div>
                </div>
            </div>
        </div>
    </div>
    <?= view::load_scripts() ?>
    <?
    if (!defined("DISABLE_TRACKERS")) {
        echo view::load("tracker/global_tracker");
    }
    ?>
</div>
<p style="text-align:center;font-size:12px;color:#666;margin-top:3px">
    Bu site <a href="https://www.teknoeticaret.com" target="_blank"><strong>Tekno E-Ticaret</strong></a> altyapısı ile hizmet veriyor.
</p>
