<div id="footer">
    <div class="footerbottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-3"><span class="footervalign"><?= \TeknoETicaret\Config\Settings::get('site.name') ?> &copy; <?= date('Y') ?> <br> Her hakkı saklıdır.</span></div>
                <div class="col-xs-6 text-center"><img src="<?= $themeDir ?>/img/footer-logo.jpg" width="467" height="29"></div>
                <div class="col-xs-3 text-center"><p>Bu site <a href="http://www.teknomavi.com" target="_blank">Tekno E-Ticaret</a> altyapısı ile hazırlanmıştır.</p></div>

            </div>
        </div>
    </div>
    <?= view::load_scripts() ?>
    <?
    if (!defined("DISABLE_TRACKERS")) {
        echo view::load("tracker/global_tracker");
    }
    ?>
</div>
