<!DOCTYPE html>
<html lang="tr">
<?= view::load("head") ?>
<body lang="tr">
<?= view::facebook_sdk() ?>
<?= view::load("header") ?>
<section>
    <?= view::showMessages('class="messageBox container" style="display:none"') ?>
    <div class="container">
        <? if (view::has_blocks()) { ?>
            <div class="row">
                <? view::show_blocks("col-xs-12 col-md-3 col-sm-3") ?>
                <? view::show_contents("col-xs-12 col-sm-9 col-md-9") ?>
            </div>
        <? } else { ?>
            <? view::show_contents() ?>
        <? } ?>
    </div>
</section>
<!-- container sonu -->
<?= view::load("footer") ?>
</body>
</html>
